### ISSUE TITLE
mention serializer? soon?

### ISSUE THREAD

**Issue by samselikoff** [jsncmgs1/mirage-tutorial#1]
Hey, thanks so much for writing this up!

I just wanted you to be aware of the [json-api-serializer](https://github.com/samselikoff/ember-cli-mirage/tree/json-api-serializer) branch that is currently my #1 priority. I expect to have this landed in 3-5 weeks? I'm not sure if you want to mention it, but basically it will take care of a lot of the payload transforming parts of the code.

Anyway, just wanted to put it on your radar. You'll still be able to use the code as you have it once the serializers land. Thanks again!

**Comment by jsncmgs1** [comment]
No problem!  I'll mention it in the tutorial and update it when that branch lands.
